### ISSUE TITLE
Why the estimation of CATE is calculated as below?

### ISSUE THREAD

**Issue by ghost** [kochbj/Deep-Learning-for-Causal-Inference#1]
In [Tutorial 1](Deep-Learning-for-Causal-Inference/Tutorial_1_Introduction_to_Deep_Learning_for_Causal_Inference_on_Observables.ipynb), it is calculated according to the following equation:
![](https://render.githubusercontent.com/render/math?math=%5Chat%7BCATE%7D%3D%281-2t%29%28%5Chat%7B%7By%7D%7D%28t%29-%5Chat%7By%7D%281-t%29%29&mode=inline)
No matter t equals 0 or 1, the value is opposite to what it is supposed to be.

**Comment by kochbj** [comment]
Hi Ywandung,

Sorry for the slow response and thanks for catching this! You're right that the terms should be reversed so I fixed it. FWIW, this formulation isn't used anywhere in the code.

Please let me know if you see any other issues; I should probably take another pass through the notation and make it more standard anyways.

Best,
Bernie
