### ISSUE TITLE
Tutorial for multi treatments 

### ISSUE THREAD

**Issue by CoteDave** [kochbj/Deep-Learning-for-Causal-Inference#4]
Hi,

Very usefull and great tutorials! Any plans to add a multi treatments tutorial with tarnet or dragonnet ?

Thanks !

**Comment by kochbj** [comment]
Hi,

Thank you for your interest! I had not planned to add additional tutorials at this time; so busy with other things. But hopefully this is helpful:

1. Should be fairly straightforward to adapt TarNet for multiple treatments. Simply add more heads and make sure the loss only feeds the head that is being used.

2. For adaptation of Dragonnet, check out these comments by Victor Veitch: https://github.com/claudiashi57/dragonnet/issues/4

Feel free to respond, if you have specific questions and I'll do my best to answer.

All the best,
Bernie
