### ISSUE TITLE
Question about dragonnet ATE estimation

### ISSUE THREAD

**Issue by xiaogangzhu** [kochbj/Deep-Learning-for-Causal-Inference#9]
Hi,

I have read the tutorial and it is really detailed and helpful! Thanks a lot!

But I got a question and hope you can help me. So in dragonnet implementation in tutorial 3, we estimate our target with 2 method, one is ATE and another is TARREG_CATE. So my question is 
1. Is TARREG_CATE actually the ATE if we take mean of it? If it is, when we try to get the better estimation of ATE, should we choose ATE or TARREG_CATE?

**Comment by kochbj** [comment]
The expectation of TARREG_CATE. Targeted regularization is designed to sharpen your estimation of the ATE, not actually to estimate HTEs.

Hope that helps!
